[target.aarch64-unknown-linux-gnu]
pre-build = ["PB_REL=https://github.com/protocolbuffers/protobuf/releases && curl -LO $PB_REL/download/v21.9/protoc-21.9-linux-x86_64.zip && unzip protoc-21.9-linux-x86_64.zip -d $HOME/.local && rm -rf protoc-21.9-linux-x86_64.zip && export PATH=$PATH:$HOME/.local/bin" ]
