# DSCP Docker Compose file
# This is designed to help compile and run the DSCP node.
# It only works in --dev more but if you want to setup a multi-nodes, read
# docker/Dockerfile
# You can connect the frontend on port 9944
# RUN:
# docker-compose up -d
# docker-compose up -d dev
# KNOCKDOWN:
# docker-compose down
# ATTACH:
# docker-compose exec dscp_node_dev bash
# ENVIRONMENTOPTIONS:
# IDENTITY (optional): custom/null/alice/bob/charlie/dave/eve/ferdie
# VALIDATOR (optional): null/true
# CHAIN (optional): null/chain_name
# WS,RPC,CORS (optional): null/true, null/true, null/all
# BOOTNODES (optional): null/NODE_URL,NODE_URL2/etc
# NODEKEY (optional): null/key
# e.g: - BOOTNODES=/ip4/192.168.0.1/tcp/30333/p2p/Qme6f4bVFaS4AwTydZT4UesE4GS8ZBL5wD1RXq5eEdKYUH

version: '3'

services:

    dev:
        image: dscp-substrate-node:latest
        container_name: dscp_node_dev
        build:
            dockerfile: ./Dockerfile
            context: .
        #tty: true
        #stdin_open: true
        ports:
            - 30333:30333
            - 9944:9944
            - 9933:9933
        environment:
            - IDENTITY=dev
            - WS=true
            - RPC=true
            - CORS=all
        restart: on-failure
