//! Autogenerated weights for pallet_simple_nft
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-06-14, STEPS: [], REPEAT: 1, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: None, WASM-EXECUTION: Interpreted, CHAIN: None, DB CACHE: 128

// Executed Command:
// ./target/release/dscp-node
// benchmark
// --pallet
// pallet_simple_nft
// --extrinsic
// run_process
// --output
// ./weights/

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
    fn run_process(i: usize, o: usize) -> Weight;
}

/// Weight functions for pallet_simple_nft.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn run_process(i: usize, o: usize) -> Weight {
        Weight::from_ref_time(0 as u64)
            // Standard Error: 7_000
            .saturating_add((Weight::from_ref_time(14_228_228)).saturating_mul(i as u64))
            // Standard Error: 7_000
            .saturating_add((Weight::from_ref_time(8_026_000)).saturating_mul(o as u64))
            .saturating_add(T::DbWeight::get().reads(1 as u64))
            .saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1 as u64))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(o as u64)))
    }
}

impl WeightInfo for () {
    fn run_process(_: usize, _: usize) -> Weight {
        Weight::from_ref_time(0 as u64)
    }
}
