
//! Autogenerated weights for `pallet_process_validation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.1.0
//! DATE: 2025-05-02, STEPS: `50`, REPEAT: `1000`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `FNQGF7746D.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/production/sqnc-node
// benchmark
// pallet
// --pallet
// pallet-process-validation
// --extrinsic
// *
// --repeat
// 1000
// --output
// ./runtime/src/weights

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_process_validation`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_process_validation::WeightInfo for WeightInfo<T> {
	/// Storage: `ProcessValidation::VersionModel` (r:1 w:1)
	/// Proof: `ProcessValidation::VersionModel` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `ProcessValidation::ProcessModel` (r:1 w:1)
	/// Proof: `ProcessValidation::ProcessModel` (`max_values`: None, `max_size`: Some(39150), added: 41625, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 251]`.
	fn create_process(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `168`
		//  Estimated: `42615`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_574_450, 0)
			.saturating_add(Weight::from_parts(0, 42615))
			// Standard Error: 92
			.saturating_add(Weight::from_parts(292_893, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ProcessValidation::ProcessModel` (r:1 w:1)
	/// Proof: `ProcessValidation::ProcessModel` (`max_values`: None, `max_size`: Some(39150), added: 41625, mode: `MaxEncodedLen`)
	/// Storage: `ProcessValidation::VersionModel` (r:1 w:0)
	/// Proof: `ProcessValidation::VersionModel` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn disable_process() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226`
		//  Estimated: `42615`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 42615))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ProcessValidation::ProcessModel` (r:1 w:0)
	/// Proof: `ProcessValidation::ProcessModel` (`max_values`: None, `max_size`: Some(39150), added: 41625, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 251]`.
	fn validate_process(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `171 + r * (16 ±0)`
		//  Estimated: `42615`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_152_319, 0)
			.saturating_add(Weight::from_parts(0, 42615))
			// Standard Error: 74
			.saturating_add(Weight::from_parts(170_685, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `ProcessValidation::ProcessModel` (r:1 w:0)
	/// Proof: `ProcessValidation::ProcessModel` (`max_values`: None, `max_size`: Some(39150), added: 41625, mode: `MaxEncodedLen`)
	fn validate_process_min() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `42615`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 42615))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `ProcessValidation::ProcessModel` (r:1 w:0)
	/// Proof: `ProcessValidation::ProcessModel` (`max_values`: None, `max_size`: Some(39150), added: 41625, mode: `MaxEncodedLen`)
	fn validate_process_max() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4187`
		//  Estimated: `42615`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(49_000_000, 0)
			.saturating_add(Weight::from_parts(0, 42615))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
