apiVersion: v2
name: dscp-node
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
description: A Helm chart to deploy DSCP nodes
type: application
version: 4.3.1
appVersion: "4.3.1"
